version: '3.8'

services:
  angular-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/saejardindecocagne
    volumes:
      - ./server/saejardindecocagne.json:/app/saejardindecocagne.json # Montage du fichier JSON
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: saejardindecocagne
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
