# Étape 1 : Utilisation de l'image Node.js
FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["node", "server.js"] # Assurez-vous que votre point d'entrée est correct
