name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-client:
    name: Build & Test Client (Angular)
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: |
        cd client
        npm install

    - name: Run Unit Tests with Firefox
      run: |
        cd client
        npm run test -- --watch=false --browsers=FirefoxHeadless

    - name: Build Angular App
      run: |
        cd client
        npm run build -- --prod

  build-server:
    name: Build Server (Node.js)
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: |
        cd server
        npm install
