name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-client:
    name: Build Client (Angular)
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: client/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install Dependencies
      run: |
        cd client
        npm install

    - name: Run Tests
      run: |
        cd client
        npm test

    - name: Build Angular App
      run: |
        cd client
        npm run build
